### ISSUE TITLE
Bind errors while running Kitura and Kitura-NIO tests

### ISSUE THREAD

**Issue by pushkarnk** [IBM-Swift/Kitura-NIO#2]
With SwiftNIO, Channel.close() calls close(socket) which moves the underlying socket to the TIMED_WAIT state. In this state, subsequent bind calls fail, until the socket moves out of the TIMED_WAIT state and is actually closed. Kitura tests fail frequently with this error. While using Kitura-net that uses BlueSocket, I can see a shutdown(socket) being issued before close(socket). That may be the reason why this failure isn't seen with KituraNet. Needs investigation.

We can workaround this using `HTTPServer.allowPortReuse = true`

**Comment by pushkarnk** [comment]
We should try using a ephemeral ports for all the tests.

**Comment by weissi** [comment]
@pushkarnk setting 

      .serverChannelOption(ChannelOptions.socket(SocketOptionLevel(SOL_SOCKET), SO_REUSEADDR), value: 1)

should fix that. I reckon KituraNet just sets that automatically whilst NIO wants the user to specify it explicity.

**Comment by ianpartridge** [comment]
@pushkarnk ^ did you see this?

**Comment by pushkarnk** [comment]
@ianpartridge Yes, we tried `SO_REUSEADDR` in the past and it doesn't solve this problem. 

@weissi I remember discussing this issue with you over Slack back in May. `SO_REUSEADDR` wasn't helping us and you suggested we try `SO_REUSEPORT`.

**Comment by pushkarnk** [comment]
@weissi Now I recall it better, we needed `SO_REUSEPORT` for a particular test called `testServersSharingPort`. Looks like `SO_REUSEADDR` is enough for this issue.

**Comment by weissi** [comment]
@pushkarnk yes, `testServersSharingPort` sounds like two servers bind on the same port which would be `SO_REUSEPORT` (and a new enough Linux version)

**Comment by weissi** [comment]
in any case, I'd recommend `SO_REUSEADDR` for all tests and `SO_REUSEPORT` for the ones where you actually need to have two (or more) servers bind to _the same port at the same time_.

**Comment by pushkarnk** [comment]
@weiss This is the gist of the problem we're facing using both `SO_REUSEADDR` and `SO_REUSEPORT`

Consider this NIO program (note the commented line of code):
```
import NIO 

let bootstrap1 = ServerBootstrap(group: MultiThreadedEventLoopGroup(numberOfThreads: System.coreCount))
    .serverChannelOption(ChannelOptions.socket(SocketOptionLevel(SOL_SOCKET), SO_REUSEADDR), value: 1)  
   // .serverChannelOption(ChannelOptions.socket(SocketOptionLevel(SOL_SOCKET), SO_REUSEPORT), value: 0)
    .childChannelOption(ChannelOptions.socket(IPPROTO_TCP, TCP_NODELAY), value: 1)
var serverChannel1 = try! bootstrap1.bind(host: "0.0.0.0", port: 8080).wait()

let channel = try! ClientBootstrap(group: MultiThreadedEventLoopGroup(numberOfThreads: 1)) 
    .connect(host: "localhost", port: 8080).wait()

print("channel", channel)

try! serverChannel1.close().wait()

_ = try! bootstrap1.bind(host: "0.0.0.0", port: 8080).wait()
```

Run the above program. You should see no error.

Now, remove the comment and include that line of code:
```
import NIO 

let bootstrap1 = ServerBootstrap(group: MultiThreadedEventLoopGroup(numberOfThreads: System.coreCount))
    .serverChannelOption(ChannelOptions.socket(SocketOptionLevel(SOL_SOCKET), SO_REUSEADDR), value: 1)  
    .serverChannelOption(ChannelOptions.socket(SocketOptionLevel(SOL_SOCKET), SO_REUSEPORT), value: 0)
    .childChannelOption(ChannelOptions.socket(IPPROTO_TCP, TCP_NODELAY), value: 1)
var serverChannel1 = try! bootstrap1.bind(host: "0.0.0.0", port: 8080).wait()

let channel = try! ClientBootstrap(group: MultiThreadedEventLoopGroup(numberOfThreads: 1)) 
    .connect(host: "localhost", port: 8080).wait()

print("channel", channel)

try! serverChannel1.close().wait()

_ = try! bootstrap1.bind(host: "0.0.0.0", port: 8080).wait()
```

Wait until `netstat -antup` does NOT show an entry for `127.0.0.0:8080`.

Compile and run the second program. This crashes with a bind error!

This means, `not setting SO_REUSEPORT` has a different effect than `setting SO_REUSEPORT = 0`.  I'd think they are the same! 

Is this expected? Perhaps its something to do with the loopback connection?

cc @nethraravindran

**Comment by nethraravindran** [comment]
@pushkarnk @saiHemak setting `SO_REUSEPORT` as the first resolves the issue.

```
import NIO 

let bootstrap1 = ServerBootstrap(group: MultiThreadedEventLoopGroup(numberOfThreads: System.coreCount))
     .serverChannelOption(ChannelOptions.socket(SocketOptionLevel(SOL_SOCKET), SO_REUSEPORT), value: 0)
    .serverChannelOption(ChannelOptions.socket(SocketOptionLevel(SOL_SOCKET), SO_REUSEADDR), value: 1)  
  
    .childChannelOption(ChannelOptions.socket(IPPROTO_TCP, TCP_NODELAY), value: 1)
var serverChannel1 = try! bootstrap1.bind(host: "0.0.0.0", port: 8080).wait()

let channel = try! ClientBootstrap(group: MultiThreadedEventLoopGroup(numberOfThreads: 1)) 
    .connect(host: "localhost", port: 8080).wait()

print("channel", channel)

try! serverChannel1.close().wait()

_ = try! bootstrap1.bind(host: "0.0.0.0", port: 8080).wait()
```

**Comment by weissi** [comment]
thanks @pushkarnk you uncovered an ~~amazing~~ embarrassing NIO bug: We currently only store one socket option value per _type_. Ie. only one of `ChannelOptions.socket`. So setting `SO_REUSEADDR` will unset all other `ChannelOptions.socket(*)` that were set before... Working on a fix, have a failing test already.

**Comment by nethraravindran** [comment]
@saiHemak ^

**Comment by weissi** [comment]
I'm working on https://github.com/apple/swift-nio/pull/597 to fix it and will release in 1.9.3

**Comment by nethraravindran** [comment]
Thanks @weissi and @pushkarnk 

PR https://github.com/IBM-Swift/Kitura-NIO/pull/82
